version: '3.8'
services:
  web:
    build: .
    container_name: news_crawler
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python crawl.py
    networks:
      - english-vocabulary-network

networks:
  english-vocabulary-network:
    external: true