version: '3.8'
services:
  web:
    build: .
    container_name: news_crawler
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: python main.py
    networks:
      - mongodb_default

networks:
  mongodb_default:
    external: true